# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - locacarftc

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js version 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm" # Adiciona cache para acelerar instalações futuras

            - name: Install build dependencies (for node-gyp)
              run: sudo apt-get update && sudo apt-get install -y build-essential python3

            - name: Install dependencies, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  npm run test --if-present

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: |
                      .
                      !node_modules/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        permissions:
            id-token: write # Necessário para login sem senha no Azure (OIDC)

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Set up Node.js version 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm"

            - name: Install production dependencies
              run: npm install --production

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5292817AB2CF47908E2E4D7BEA890914 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AE8041DAD5414423A4491F9E50871A9B }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D667D41FDF834472BFF556836D8B0E30 }}

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "locacarftc"
                  slot-name: "Production"
                  package: .
